### ISSUE TITLE
Kurucz atmosphere model with Teff=50000 and logg=5.0

### ISSUE THREAD

**Issue by MingjieJian** [sczesla/PyAstronomy#48] opened 2020-06-30 08:47 UTC
Hi Stefan,

I am not so sure if this should be an issue or not. I am checking the Kurucz atmosphere model grids, and found that in the website, there are models with Teff=50000K and logg=5.0 dex, but I got a PyValError when I try `model = pyasl.getKuruczModel(50000, 5.0, 0.0)`. Is this intended to raise an error?

**Comment by sczesla** [comment] 2020-06-30 11:44
Hi,  Thanks for reporting this. This is not intended behavior. There was a bug (or rather a logical error), which prevented the last model in the file from being added to the list of models. This should be fixed now in the development version. Cheers, Stefan

**Closed by sczesla** 2020-06-30 11:44 UTC

**Comment by MingjieJian** [comment] 2020-06-30 12:12
Thank you Stefan! Would like to see the full models in the future release.

**Comment by sczesla** [comment] 2020-07-02 09:10
Cool, I drafted a release (0.15.1) with this inlcuded.
